// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using joia_web_dotnet_infra;

#nullable disable

namespace joia_web_dotnet_infra.Migrations
{
    [DbContext(typeof(joiaDbContext))]
    [Migration("20230403225745_transacao")]
    partial class transacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotificacaoPessoa", b =>
                {
                    b.Property<int>("NotificacoesId")
                        .HasColumnType("int");

                    b.Property<int>("PessoasId")
                        .HasColumnType("int");

                    b.HasKey("NotificacoesId", "PessoasId");

                    b.HasIndex("PessoasId");

                    b.ToTable("NotificacaoPessoa");
                });

            modelBuilder.Entity("PecaTransacao", b =>
                {
                    b.Property<int>("PecasId")
                        .HasColumnType("int");

                    b.Property<int>("TransacoesId")
                        .HasColumnType("int");

                    b.HasKey("PecasId", "TransacoesId");

                    b.HasIndex("TransacoesId");

                    b.ToTable("PecaTransacao");
                });

            modelBuilder.Entity("joia_web_dotnet_domain.Entities.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.Property<int>("PecaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PecaId");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("joia_web_dotnet_domain.Entities.Imagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PecaId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PecaId");

                    b.ToTable("Imagens");
                });

            modelBuilder.Entity("joia_web_dotnet_domain.Entities.Metal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Pedra")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("PrecoPorGrama")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Metais");
                });

            modelBuilder.Entity("joia_web_dotnet_domain.Entities.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("joia_web_dotnet_domain.Entities.Peca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetalId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("Publico")
                        .HasColumnType("tinyint");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<byte>("Tipo")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("MetalId");

                    b.ToTable("Pecas");
                });

            modelBuilder.Entity("joia_web_dotnet_domain.Entities.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("joia_web_dotnet_domain.Entities.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("PecaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PecaId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("joia_web_dotnet_domain.Entities.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdministradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("nomeComprador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeVendedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("tipo")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("joia_web_dotnet_domain.Entities.Administrador", b =>
                {
                    b.HasBaseType("joia_web_dotnet_domain.Entities.Pessoa");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("joia_web_dotnet_domain.Entities.Cliente", b =>
                {
                    b.HasBaseType("joia_web_dotnet_domain.Entities.Pessoa");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("NotificacaoPessoa", b =>
                {
                    b.HasOne("joia_web_dotnet_domain.Entities.Notificacao", null)
                        .WithMany()
                        .HasForeignKey("NotificacoesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("joia_web_dotnet_domain.Entities.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("PessoasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PecaTransacao", b =>
                {
                    b.HasOne("joia_web_dotnet_domain.Entities.Peca", null)
                        .WithMany()
                        .HasForeignKey("PecasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("joia_web_dotnet_domain.Entities.Transacao", null)
                        .WithMany()
                        .HasForeignKey("TransacoesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("joia_web_dotnet_domain.Entities.Avaliacao", b =>
                {
                    b.HasOne("joia_web_dotnet_domain.Entities.Cliente", "Cliente")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("joia_web_dotnet_domain.Entities.Peca", "Peca")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("PecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Peca");
                });

            modelBuilder.Entity("joia_web_dotnet_domain.Entities.Imagem", b =>
                {
                    b.HasOne("joia_web_dotnet_domain.Entities.Peca", "Peca")
                        .WithMany("Imagens")
                        .HasForeignKey("PecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peca");
                });

            modelBuilder.Entity("joia_web_dotnet_domain.Entities.Peca", b =>
                {
                    b.HasOne("joia_web_dotnet_domain.Entities.Metal", "Metal")
                        .WithMany("Pecas")
                        .HasForeignKey("MetalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metal");
                });

            modelBuilder.Entity("joia_web_dotnet_domain.Entities.Reserva", b =>
                {
                    b.HasOne("joia_web_dotnet_domain.Entities.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("joia_web_dotnet_domain.Entities.Peca", "Peca")
                        .WithMany("Reservas")
                        .HasForeignKey("PecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Peca");
                });

            modelBuilder.Entity("joia_web_dotnet_domain.Entities.Transacao", b =>
                {
                    b.HasOne("joia_web_dotnet_domain.Entities.Administrador", "Administrador")
                        .WithMany("Transacoes")
                        .HasForeignKey("AdministradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrador");
                });

            modelBuilder.Entity("joia_web_dotnet_domain.Entities.Administrador", b =>
                {
                    b.HasOne("joia_web_dotnet_domain.Entities.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("joia_web_dotnet_domain.Entities.Administrador", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("joia_web_dotnet_domain.Entities.Cliente", b =>
                {
                    b.HasOne("joia_web_dotnet_domain.Entities.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("joia_web_dotnet_domain.Entities.Cliente", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("joia_web_dotnet_domain.Entities.Metal", b =>
                {
                    b.Navigation("Pecas");
                });

            modelBuilder.Entity("joia_web_dotnet_domain.Entities.Peca", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Imagens");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("joia_web_dotnet_domain.Entities.Administrador", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("joia_web_dotnet_domain.Entities.Cliente", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
